# Generated by Django 5.1.2 on 2024-11-01 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BreedersHub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='breed',
            name='animal_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='breed',
            name='breed_id',
            field=models.CharField(default=0, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='breed',
            name='height',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='breed',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='breed',
            name='life_span',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='breed',
            name='origin',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='breed',
            name='temperament',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='breed',
            name='weight',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
