# Generated by Django 5.1.2 on 2024-11-01 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BreedersHub', '0002_breed_animal_type_breed_breed_id_breed_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='breeder',
            name='affisso',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
