# Generated by Django 5.1.2 on 2024-11-01 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BreedersHub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('maschio', 'Maschio'), ('femmina', 'Femmina')], max_length=10)),
                ('age', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=50)),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('photo', models.ImageField(upload_to='dogs/')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_dogs_same_breed', to='BreedersHub.breed')),
            ],
        ),
    ]
