# Generated by Django 5.1.2 on 2024-11-02 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='loi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dog',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
