# Generated by Django 5.1.2 on 2024-11-02 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_dog_loi_alter_dog_height'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogForSale',
            fields=[
                ('dog_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='animals.dog')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_shippable', models.BooleanField(default=False)),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='contracts/')),
            ],
            bases=('animals.dog',),
        ),
        migrations.AddField(
            model_name='dog',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring_father', to='animals.dog'),
        ),
        migrations.AddField(
            model_name='dog',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring_mother', to='animals.dog'),
        ),
    ]
