# Generated by Django 5.1.2 on 2024-11-03 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_dogforsale_dog_father_dog_mother'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='age',
        ),
        migrations.AddField(
            model_name='dog',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
