# Generated by Django 5.1.2 on 2024-11-03 00:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_remove_dog_age_dog_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.date(2022, 6, 20), null=True),
        ),
    ]
