# Generated by Django 5.1.2 on 2024-11-03 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BreedersHub', '0004_rename_affisso_breeder_kennel_name'),
        ('animals', '0005_alter_dog_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Litter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('litter_info', models.TextField()),
                ('date_of_birth', models.DateField(auto_now_add=True)),
                ('father', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='father_litters', to='BreedersHub.dog')),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mother_litters', to='BreedersHub.dog')),
            ],
        ),
        migrations.AddField(
            model_name='dog',
            name='litter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dogs', to='animals.litter'),
        ),
    ]
