# Generated by Django 5.1.2 on 2024-11-03 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0007_rename_litter_info_litter_litter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
    ]
